<h3 class="policy-heading policy-heading-teal">Corporate Social Responsibility Policy</h3>
<p>Riot Labz Private Limited has vision to do business with a smile for customer delight and a commitment to society. Company has built strong value of trust and earned due respect from its clients, business associates, customers and society at large. Company is committed to implement Corporate Social Responsibility (CSR) Policy through Investments in various areas as defined below. It is the intent of the Company to make a positive difference to society by continuous efforts to make the life of poor and needy persons better.</p>
<h3 class="policy-heading policy-heading-teal">Policy</h3>
<p>This Policy is called as "Corporate Social Responsibility Policy". The policy has been approved by the Board of Directors of the Company. Company shall invest such amount as decided by the Board on any of the following projects or programs.</p>
<h3 class="policy-heading policy-heading-teal">Area of CSR Projects or Programs</h3>
<p>Company plans to undertake CSR projects or programs under following area as approved by the Board either directly or through some registered trust or a registered society or a section 8 company established by Company or its subsidiary or associate company:</p>
<p class="policy-clause">(i) eradicating hunger, poverty and malnutrition, promoting preventive health care and sanitation, including contribution to the Swach Bharat Kosh set up by the Central Government for the promotion of sanitation, and making available safe drinking water;</p>
<p class="policy-clause">(ii) promoting education, including special education and employment enhancing vocational skills especially among children, women, elderly and the differently abled and livelihood enhancement projects;</p>
<p class="policy-clause">(iii) promoting gender equality, empowering women, setting up homes and hostels for women and orphans; setting up old age homes, day care centers and such other facilities for senior citizen and measures for reducing inequalities faced by socially and economically backward groups;</p>
<p class="policy-clause">(iv) ensuring environmental sustainability, ecological balance, protection of flora and fauna, animal welfare, agroforestry, conservation of natural resources and maintaining quality of soil, air and water; including contribution to the Clean Ganga Fund set-up by the Central Government for rejuvenation of river Ganga;</p>
<p class="policy-clause">(v) protection of national heritage, art and culture including restoration of buildings and sites of historical importance and works of art; setting up public libraries; promotion and development of traditional arts and handicrafts;</p>
<p class="policy-clause">(vi) measures for the benefit of armed forces ventures, war widows and their dependents;</p>
<p class="policy-clause">(vii) training to promote rural sports, nationally recognized sports, para-olympics sports and Olympic sports;</p>
<p class="policy-clause">(viii) contribution to the prime Minister's National Relief Fund or any other fund set up by the Central Government for socio-economic development and relief and welfare of the Scheduled Castes, the Scheduled Tribes, other backward castes, minorities and women;</p>
<p class="policy-clause">(ix) contributions or funds provided to technology incubators located within academic institutions which are approved by the Central Government;</p>
<p class="policy-clause">(x) rural development projects.</p>
<p class="policy-clause">(xi) slum area development.</p>
<p>Provided that if the expenditure is incurred through trust/society/other company, Riot Labz Private Limited shall specify the project or program to be undertaken through these entities, the modalities of utilization of funds on such projects and programs and the monitoring and reporting mechanism.</p>